Attempt to implement warpsize with overload_attribute
This presently has a problem:

```
numba.cuda.tests.cudapy.test_intrinsics.TestCudaIntrinsic.test_simple_warpsize
````

fails with:

```
numba.core.errors.TypingError: Failed in cuda mode pipeline (step: nopython frontend)
No implementation of function Function(<function cuda_warpsize at 0x7fe016068af0>) found for signature:

 >>> cuda_warpsize(Module(<module 'numba.cuda' from '/home/gmarkall/numbadev/numba/numba/cuda/__init__.py'>))

There are 2 candidate implementations:
  - Of which 1 did not match due to:
  Overload in function 'cuda_warpsize': File: numba/cuda/intrinsics.py: Line 114.
    With argument(s): '(Module(<module 'numba.cuda' from '/home/gmarkall/numbadev/numba/numba/cuda/__init__.py'>))':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   Internal error at <numba.core.typeinfer.CallConstraint object at 0x7fdfef934790>.
   Function resolution cannot find any matches for function '<intrinsic _warpsize>' for the current hardware: '<class 'numba.core.extending_hardware.CPU'>'.
   During: resolving callee type: Function(<intrinsic _warpsize>)
   During: typing of call at /home/gmarkall/numbadev/numba/numba/cuda/intrinsics.py (121)

   Enable logging at debug level for details.

   File "numba/cuda/intrinsics.py", line 121:
       def get(mod):
           return _warpsize()
           ^

  raised from /home/gmarkall/numbadev/numba/numba/core/typeinfer.py:1071
  - Of which 1 did not match due to:
  Overload in function 'cuda_warpsize': File: numba/cuda/intrinsics.py: Line 114.
    With argument(s): '(Module(<module 'numba.cuda' from '/home/gmarkall/numbadev/numba/numba/cuda/__init__.py'>))':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   Internal error at <numba.core.typeinfer.CallConstraint object at 0x7fdfef92acd0>.
   Function resolution cannot find any matches for function '<intrinsic _warpsize>' for the current hardware: '<class 'numba.core.extending_hardware.CPU'>'.
   During: resolving callee type: Function(<intrinsic _warpsize>)
   During: typing of call at /home/gmarkall/numbadev/numba/numba/cuda/intrinsics.py (121)

   Enable logging at debug level for details.

   File "numba/cuda/intrinsics.py", line 121:
       def get(mod):
           return _warpsize()
           ^

  raised from /home/gmarkall/numbadev/numba/numba/core/typeinfer.py:1071

During: typing of get attribute at /home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_intrinsics.py (119)

File "numba/cuda/tests/cudapy/test_intrinsics.py", line 119:
def simple_warpsize(ary):
    ary[0] = cuda.warpsize
```

The main suspicious item is that Numba seems to think the current
hardware is a CPU.