[314] [py] Expect complex math failures
This skips the following test case failures on 3.14:

```
======================================================================
FAIL: test_div_npm (numba.tests.test_complex.TestComplex.test_div_npm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/numba/numba/tests/test_complex.py", line 118, in test_div_npm
    self.test_div(flags=no_pyobj_flags)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/numba/numba/tests/test_complex.py", line 115, in test_div
    self.run_binary(div_usecase, value_types, values, flags=flags)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/numba/numba/tests/test_complex.py", line 68, in run_binary
    self.assertPreciseEqual(got, expected, prec=prec,
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
                            ulps=ulps, msg=msg)
                            ^^^^^^^^^^^^^^^^^^^
  File "/numba/numba/tests/support.py", line 465, in assertPreciseEqual
    self.fail("when comparing %s and %s: %s" % (first, second, failure_msg))
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: when comparing (nan+nanj) and 0j: nan != 0.0 within nan delta (nan difference) : for input ((-0-0j), (-inf-infj)) with prec 'double'

======================================================================
FAIL: test_log_base_npm (numba.tests.test_complex.TestCMath.test_log_base_npm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/numba/numba/tests/test_complex.py", line 211, in test_log_base_npm
    self.test_log_base(flags=no_pyobj_flags)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/numba/numba/tests/test_complex.py", line 207, in test_log_base
    self.run_binary(log_base_usecase, value_types, values, flags=flags,
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    ulps=3)
                    ^^^^^^^
  File "/numba/numba/tests/test_complex.py", line 68, in run_binary
    self.assertPreciseEqual(got, expected, prec=prec,
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
                            ulps=ulps, msg=msg)
                            ^^^^^^^^^^^^^^^^^^^
  File "/numba/numba/tests/support.py", line 465, in assertPreciseEqual
    self.fail("when comparing %s and %s: %s" % (first, second, failure_msg))
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: when comparing (nan+nanj) and 0j: nan != 0.0 within nan delta (nan difference) : for input ((-0+1j), (-inf+nanj)) with prec 'double'
```