Fix setitem/getitem resolvers
To add an overload for a setitem (https://github.com/Quansight/numba-xnd/blob/48b4256bb1cd9bf5e33c0ee889cdee784a8a8591/numba_xnd/libxnd.py#L152-L159), I needed to update these `kws` to be dictionaries instead of tuples. Otherwise, numba would complain with:

Traceback (most recent call last):
  File "/Users/saul/p/numba-xnd/numba/numba/typeinfer.py", line 142, in propagate
    constraint(typeinfer)
  File "/Users/saul/p/numba-xnd/numba/numba/typeinfer.py", line 610, in __call__
    self.signature = sig
  File "/usr/local/miniconda3/envs/numba-xnd/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/saul/p/numba-xnd/numba/numba/errors.py", line 603, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/Users/saul/p/numba-xnd/numba/numba/six.py", line 659, in reraise
    raise value
numba.errors.InternalError: typer() argument after ** must be a mapping, not tuple