Add physical limits for CC 7.0 / 7.5 to autotune
Running the testsuite with a CC 7.0 or later GPU results in the
following error:

```
======================================================================
ERROR: test_autotune (numba.cuda.tests.cudapy.test_deprecation.TestCudaDebugInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/cudadrv/autotune.py", line 245, in warp_occupancy
    limits = PHYSICAL_LIMITS[cc]
KeyError: (7, 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_deprecation.py", line 29, in test_autotune
    foo.autotune
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 727, in autotune
    at = AutoTuner(info=cufunc.attrs, cc=cufunc.device.compute_capability)
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/cudadrv/autotune.py", line 49, in __init__
    self._table = warp_occupancy(info=info, cc=cc)
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/cudadrv/autotune.py", line 248, in warp_occupancy
    % ".".join(str(c) for c in cc))
ValueError: 7.0 is not a supported compute capability
```

Although the autotune functionality is deprecated in favour of
using the driver API to obtain a good thread block size, this
commit adds the physical limits for Compute Capabilites 7.0 and
7.5 in order to fix the test error.

Additional shared memory configurations are supported by Volta
(0KB and 8KB) - globals for those configurations, and the 80KB
configuration supported by CC 3.7 are also added for consistency.

Tested with a Tesla V100-SXM2-16GB; the test now passes with this
commit.