remove invalid sanity check from randrange tests
The sanity check assumes that all the integers generated by `randrange`
are unique implicity by converting to a `set`, however `randrange` can
not make such guarantees. The reason we are removing this is because it
makes the test unstable and causes radom failures every so often.

The resulting error looks like:

```
======================================================================
FAIL: test_random_randrange (numba.tests.test_random.TestRandom)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/opt/conda/envs/testenv_d03ff656-b9e2-4389-a4e7-02f1435193ed/lib/python3.7/site-packages/numba/tests/test_random.py", line 430, in test_random_randrange
max_width, False)
File "/opt/conda/envs/testenv_d03ff656-b9e2-4389-a4e7-02f1435193ed/lib/python3.7/site-packages/numba/tests/test_random.py", line 397, in _check_randrange
self.assertEqual(len(ints), len(set(ints)), ints)
AssertionError: 30 != 29 : [0, 524311, 3170417, 4751491, 6340830, 10297652, 2, 2637917, 6340832, 4751489, 6340832, 25953158, 18891276, 19415587, 31507523, 23642767, 16777803, 25953155, 18891278, 21529290, 34677746, 23642765, 13, 3956864, 4227225, 4751504, 9511229, 524312, 2113607, 3956861]
----------------------------------------------------------------------
```

Where in this case the number `6340832` is the duplicate.