fix use of rstcheck in towncrier check script
This fixes the use of ``check_output`` in the script
``towncrier_rst_validator.py``. Previously, if there was an error when
running ``rstcheck`` the actual error message from that tool would just
be swallowed by the script.

The following is an example taken from a recent attempt to write a news
fragment:

```
$ python maint/towncrier_rst_validator.py --pull_request_id 9892
Found modified .rst files in directory docs/upcoming_changes from git diff:
docs/upcoming_changes/9892.improvement.rst

Found required file: docs/upcoming_changes/9892.improvement.rst

Checking naming convention.
Passed: Filename is valid

Checking file contents:

[UX] TypedDict: better error message for KeyError #9892
-------------------------------------------------------

The ``KeyError`` raised from ``__getitem__`` for the ``numba.typed.Dict`` in
case of an non-existing key now reports the value of the key. This behaviour is
in-line with regular ``dict``s via CPython.

Passed: File contents are valid

Validating RST
Traceback (most recent call last):
  File "/Users/esc/git/numba/maint/towncrier_rst_validator.py", line 107, in <module>
    output = check_output(["rstcheck", file], stderr=STDOUT, encoding="utf-8")
  File "/Users/esc/miniconda3-arm64/envs/numba_3.13/lib/python3.13/subprocess.py", line 472, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
               **kwargs).stdout
               ^^^^^^^^^
  File "/Users/esc/miniconda3-arm64/envs/numba_3.13/lib/python3.13/subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rstcheck', 'docs/upcoming_changes/9892.improvement.rst']' returned non-zero exit status 1.
```

This PR modifys the script such that the output is now:

```
$ python maint/towncrier_rst_validator.py --pull_request_id 9892                                                                                                                                  :(
Found modified .rst files in directory docs/upcoming_changes from git diff:
docs/upcoming_changes/9892.improvement.rst

Found required file: docs/upcoming_changes/9892.improvement.rst

Checking naming convention.
Passed: Filename is valid

Checking file contents:

[UX] TypedDict: better error message for KeyError #9892
-------------------------------------------------------

The ``KeyError`` raised from ``__getitem__`` for the ``numba.typed.Dict`` in
case of an non-existing key now reports the value of the key. This behaviour is
in-line with regular ``dict``s via CPython.

Passed: File contents are valid

Validating RST
Failed: rstcheck failed
docs/upcoming_changes/9892.improvement.rst:4: (WARNING/2) Inline literal start-string without end-string.
Error! Issues detected.
```