update error message and include tests
The error message has been updated to the format:

```
KeyError: <KEYVALUE>
```

... since this is what the CPython does with a regular Python dict:

```
In [1]: d = {}

In [2]: d[0]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[2], line 1
----> 1 d[0]

KeyError: 0
```

Tests for the correct message are now included.